# -*- coding: utf-8 -*-
"""representation-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-uav5jWv8tBY2X4wpQ6kofkhNEOmTJ3

Standard VQ-VAE
"""

import torch
import matplotlib.pyplot as plt
import torch.nn as nn

seed = 0
torch.manual_seed(seed)

# define dataset
amb_dim = 2
D = 1
class_per_dim = 2

bot_dim = 2

# generate data
def generate_data(n_samples, sigma=0.2):
    data = torch.zeros(n_samples, amb_dim)
    data_indices = torch.zeros(n_samples, D, dtype=torch.long)
    for i in range(D):
        data_indices[:, i] = torch.randint(0, class_per_dim, (n_samples,))
    data[:, :D] = data_indices[:, :D].float() / (class_per_dim - 1) - 1/2
    data = data + (torch.rand(n_samples, amb_dim) - 0.5) * sigma / (class_per_dim - 1)
    return data, data_indices

batch = 1000
data, _ = generate_data(batch)
#plt.scatter(data[:, 0], data[:, 1])

encoder = nn.Linear(amb_dim, bot_dim)
decoder = nn.Linear(bot_dim, amb_dim)

n_codes = 2

codes = torch.nn.Parameter(torch.rand(n_codes, bot_dim) - 0.5)

optimizer = torch.optim.Adam(list(encoder.parameters()) + list(decoder.parameters()) + [codes], lr=3e-3)

gamma = 1.0
beta = 0.25

# Collect training dynamics every save_every epochs for video
save_every = 10
hidden_history = []
codes_history = []
code_id_history = []

for i in range(1000):

    optimizer.zero_grad()

    hidden = encoder(data)  # (batch, bot_dim)

    dist = torch.norm(hidden[:, None, :] - codes[None, :, :], dim=-1)  # (batch, n_codes)
    code_id = torch.argmin(dist, dim=-1)  # (batch,)

    e = codes[code_id]  # (batch, bot_dim)

    recon = decoder(e)

    recon_loss = torch.mean((recon - data)**2)
    code_loss = torch.mean((hidden.detach() - e)**2)
    commit_loss = torch.mean((hidden - e.detach())**2)

    loss = gamma *recon_loss + code_loss + beta * commit_loss

    loss.backward()
    optimizer.step()

    if i % save_every == 0:
        with torch.no_grad():
            hidden_history.append(encoder(data).clone())
            codes_history.append(codes.data.clone())
            dist = torch.norm(hidden_history[-1][:, None, :] - codes_history[-1][None, :, :], dim=-1)
            code_id_history.append(torch.argmin(dist, dim=-1))

    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss.item(), recon_loss.item(), code_loss.item(), commit_loss.item()}")

# Build video of training dynamics in hidden space
from matplotlib.animation import FuncAnimation, FFMpegWriter, PillowWriter
import numpy as np

# Global axis limits from all frames
all_hidden = torch.cat(hidden_history, dim=0)
all_codes = torch.cat(codes_history, dim=0)
x_min = min(all_hidden[:, 0].min().item(), all_codes[:, 0].min().item())
x_max = max(all_hidden[:, 0].max().item(), all_codes[:, 0].max().item())
y_min = min(all_hidden[:, 1].min().item(), all_codes[:, 1].min().item())
y_max = max(all_hidden[:, 1].max().item(), all_codes[:, 1].max().item())
margin = 0.1
x_min -= margin; x_max += margin; y_min -= margin; y_max += margin

fig, ax = plt.subplots(figsize=(6, 6))
n_frames = len(hidden_history)

def update_frame(t):
    ax.clear()
    h = hidden_history[t]
    c = codes_history[t]
    cid = code_id_history[t]
    ax.scatter(h[:, 0].numpy(), h[:, 1].numpy(), c=cid.numpy(), cmap='tab10', s=8, alpha=0.7, vmin=0, vmax=n_codes-1)
    ax.scatter(c[:, 0].numpy(), c[:, 1].numpy(), c='k', s=120, marker='*', edgecolors='yellow', linewidths=1.5, label='codes', zorder=5)
    x_min = -1; x_max = 1; y_min = -1; y_max = 1
    ax.set_xlim(x_min, x_max)
    ax.set_ylim(y_min, y_max)
    ax.set_xlabel('hidden dim 0')
    ax.set_ylabel('hidden dim 1')
    ax.set_title(f'Epoch {t * save_every}')
    ax.set_aspect('equal')

anim = FuncAnimation(fig, update_frame, frames=n_frames, interval=80)

# Save as mp4 (requires ffmpeg) or gif as fallback
out_path = 'training_dynamics.mp4'
try:
    writer = FFMpegWriter(fps=12, metadata=dict(artist='VQ-VAE'))
    anim.save(out_path, writer=writer, dpi=100)
    print(f'Saved {out_path}')
except Exception as e:
    print(f'FFMpeg failed ({e}), saving as GIF...')
    out_path = 'training_dynamics.gif'
    anim.save(out_path, writer=PillowWriter(fps=12), dpi=300)
    print(f'Saved {out_path}')
plt.close()



"""Drifting VQ-VAE"""

import torch
import matplotlib.pyplot as plt
import torch.nn as nn

seed = 0
torch.manual_seed(seed)

# define dataset
amb_dim = 2
D = 1
class_per_dim = 2

bot_dim = 2

# generate data
def generate_data(n_samples, sigma=0.2):
    data = torch.zeros(n_samples, amb_dim)
    data_indices = torch.zeros(n_samples, D, dtype=torch.long)
    for i in range(D):
        data_indices[:, i] = torch.randint(0, class_per_dim, (n_samples,))
    data[:, :D] = data_indices[:, :D].float() / (class_per_dim - 1) - 1/2
    data = data + (torch.rand(n_samples, amb_dim) - 0.5) * sigma / (class_per_dim - 1)
    return data, data_indices

batch = 1000
data, _ = generate_data(batch)
#plt.scatter(data[:, 0], data[:, 1])

encoder = nn.Linear(amb_dim, bot_dim)
decoder = nn.Linear(bot_dim, amb_dim)

n_codes = 2

codes = torch.nn.Parameter(torch.rand(n_codes, bot_dim) - 0.5)

optimizer = torch.optim.Adam(list(encoder.parameters()) + list(decoder.parameters()) + [codes], lr=3e-3)

gamma = 1.0
beta = 0.25
tau = 0.2  # scale for potential

# View hidden state = positive sample, code = negative sample
# define force f(r) = r * exp(-r / tau), whose potential (integral) is - exp(-r / tau) * tau * (r + tau) * q1 * q2 (r is the distance between q1 and q2)
# pos2pos or neg2neg: force is repulsive
# pos2neg or neg2pos: force is attractive
# each code has charge - 1/n_codes, each hidden state has charge 1/n_hidden
def potential(r, q1, q2, tau):
    r_safe = r + 1e-8
    return torch.exp(-r_safe / tau) * tau * (r_safe + tau) * q1 * q2

# Collect training dynamics every save_every epochs for video
save_every = 10
hidden_history = []
codes_history = []
code_id_history = []

for i in range(1000):

    optimizer.zero_grad()

    hidden = encoder(data)  # (batch, bot_dim)

    dist = torch.norm(hidden[:, None, :] - codes[None, :, :], dim=-1)  # (batch, n_codes)
    code_id = torch.argmin(dist, dim=-1)  # (batch,)

    e = codes[code_id]  # (batch, bot_dim)

    recon = decoder(e)

    recon_loss = torch.mean((recon - data)**2)
    code_loss = torch.mean((hidden.detach() - e)**2)
    commit_loss = torch.mean((hidden - e.detach())**2)

    # Energy: pos2pos (hidden-hidden), neg2neg (code-code), pos2neg (hidden-code)
    # q_h (batch,), q_c (n_codes,) — per-particle charges; broadcast to pairs
    q_h = torch.ones(batch, device=hidden.device) / batch
    q_c = -torch.ones(n_codes, device=codes.device) / n_codes
    #q_c = - torch.tensor([0.3, 0.7])
    V_hh = potential(torch.cdist(hidden, hidden), q_h.unsqueeze(1), q_h.unsqueeze(0), tau)
    E_pos2pos = (V_hh.sum() - V_hh.diag().sum()) / 2  # sum over i < j
    V_cc = potential(torch.cdist(codes, codes), q_c.unsqueeze(1), q_c.unsqueeze(0), tau)
    E_neg2neg = (V_cc.sum() - V_cc.diag().sum()) / 2
    E_pos2neg = potential(torch.cdist(hidden, codes), q_h.unsqueeze(1), q_c.unsqueeze(0), tau).sum()
    energy = E_pos2pos + E_neg2neg + E_pos2neg

    loss = gamma * recon_loss + beta * energy

    loss.backward()


    optimizer.step()

    if i % save_every == 0:
        with torch.no_grad():
            hidden_history.append(encoder(data).clone())
            codes_history.append(codes.data.clone())
            dist = torch.norm(hidden_history[-1][:, None, :] - codes_history[-1][None, :, :], dim=-1)
            code_id_history.append(torch.argmin(dist, dim=-1))

    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {loss.item(), recon_loss.item(), code_loss.item(), commit_loss.item()}")

# Build video of training dynamics in hidden space
from matplotlib.animation import FuncAnimation, FFMpegWriter, PillowWriter
import numpy as np

# Global axis limits from all frames
all_hidden = torch.cat(hidden_history, dim=0)
all_codes = torch.cat(codes_history, dim=0)
x_min = min(all_hidden[:, 0].min().item(), all_codes[:, 0].min().item())
x_max = max(all_hidden[:, 0].max().item(), all_codes[:, 0].max().item())
y_min = min(all_hidden[:, 1].min().item(), all_codes[:, 1].min().item())
y_max = max(all_hidden[:, 1].max().item(), all_codes[:, 1].max().item())
margin = 0.1
x_min -= margin; x_max += margin; y_min -= margin; y_max += margin

fig, ax = plt.subplots(figsize=(6, 6))
n_frames = len(hidden_history)

def update_frame(t):
    ax.clear()
    h = hidden_history[t]
    c = codes_history[t]
    cid = code_id_history[t]
    ax.scatter(h[:, 0].numpy(), h[:, 1].numpy(), c=cid.numpy(), cmap='tab10', s=8, alpha=0.7, vmin=0, vmax=n_codes-1)
    ax.scatter(c[:, 0].numpy(), c[:, 1].numpy(), c='k', s=120, marker='*', edgecolors='yellow', linewidths=1.5, label='codes', zorder=5)
    x_min = -1.5; x_max = 1.5; y_min = -1.5; y_max = 1.5
    ax.set_xlim(x_min, x_max)
    ax.set_ylim(y_min, y_max)
    ax.set_xlabel('hidden dim 0')
    ax.set_ylabel('hidden dim 1')
    ax.set_title(f'Epoch {t * save_every}')
    ax.set_aspect('equal')

anim = FuncAnimation(fig, update_frame, frames=n_frames, interval=80)

# Save as mp4 (requires ffmpeg) or gif as fallback
out_path = 'training_dynamics.mp4'
try:
    writer = FFMpegWriter(fps=12, metadata=dict(artist='VQ-VAE'))
    anim.save(out_path, writer=writer, dpi=300)
    print(f'Saved {out_path}')
except Exception as e:
    print(f'FFMpeg failed ({e}), saving as GIF...')
    out_path = 'training_dynamics_drifting.gif'
    anim.save(out_path, writer=PillowWriter(fps=12), dpi=300)
    print(f'Saved {out_path}')
plt.close()

